// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCReu1hDFjVMaOiVkblQM5c3D9S4xYk0Bw',
    appId: '1:744770451817:web:da728a702fe6a95855e5f8',
    messagingSenderId: '744770451817',
    projectId: 'smartfarming-a2834',
    authDomain: 'smartfarming-a2834.firebaseapp.com',
    storageBucket: 'smartfarming-a2834.firebasestorage.app',
    measurementId: 'G-3W2NT3BFPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDK6LPxkmpFtW7VFD1PzRrtOrQbNSQSrs',
    appId: '1:744770451817:android:34d5a5d250a4582e55e5f8',
    messagingSenderId: '744770451817',
    projectId: 'smartfarming-a2834',
    storageBucket: 'smartfarming-a2834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7mICdV55X6ohfIkXwNPTx0BlBbE18Zmo',
    appId: '1:744770451817:ios:a8f61c5665bb60a255e5f8',
    messagingSenderId: '744770451817',
    projectId: 'smartfarming-a2834',
    storageBucket: 'smartfarming-a2834.firebasestorage.app',
    iosBundleId: 'com.example.smartFarming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7mICdV55X6ohfIkXwNPTx0BlBbE18Zmo',
    appId: '1:744770451817:ios:a8f61c5665bb60a255e5f8',
    messagingSenderId: '744770451817',
    projectId: 'smartfarming-a2834',
    storageBucket: 'smartfarming-a2834.firebasestorage.app',
    iosBundleId: 'com.example.smartFarming',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCReu1hDFjVMaOiVkblQM5c3D9S4xYk0Bw',
    appId: '1:744770451817:web:df4f0c3c7d7b4bf055e5f8',
    messagingSenderId: '744770451817',
    projectId: 'smartfarming-a2834',
    authDomain: 'smartfarming-a2834.firebaseapp.com',
    storageBucket: 'smartfarming-a2834.firebasestorage.app',
    measurementId: 'G-Q73SPQXYJR',
  );
}
